# This file is part of the YesWiki Extension archive.
# Authors : see README.md file that was distributed with this source code.
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
parameters:
  archive: 
    anonymous: 
      mysql_host: ''
      mysql_database: ''
      mysql_user: ''
      mysql_password: ''
      contact_smtp_host: ''
      contact_smtp_user: ''
      contact_smtp_pass: ''
      api_allowed_keys: []
    authorize_bypass_preupdate_backup: false
    call_archive_async: true
    max_nb_files: 10
  archive_editable_config_params:
    - archive:
      - privatePath
      - call_archive_async
      - max_nb_files
services:
  _defaults:
    autowire: true
    public: true

  YesWiki\Archive\Service\:
    resource: 'services/*'
  YesWiki\Archive\Controller\:
    resource: 'controllers/*'

  YesWiki\Archive\Controller\SecurityController:
    decorates: YesWiki\Security\Controller\SecurityController

  YesWiki\Archive\Service\ActionsBuilderService:
    decorates: YesWiki\Aceditor\Service\ActionsBuilderService
    decoration_on_invalid: null
    arguments:
      $parentActionsBuilderService: '@.inner'